Pages/Campaigns.cshtml.cs
using eVybir.Infra;
using eVybir.Pages.Shared;
using eVybir.Repos;
using Microsoft.AspNetCore.Mvc;

namespace eVybir.Pages
{
    public class CampaignsModel : LoginAwareCrudPage
    {
        public override Type PageType => typeof(Pages_Campaigns);

        public override string Title => "Campaigns";

        public async Task<IActionResult> OnPost(int camId, string camName, DateTime startDate, DateTime endDate)
        {
            if (!CheckRole(out var failed)) return failed!;
            if (camId == DEFAULT_ID)
            {
                await CampaignsDb.AddCampaign(camName, startDate.AsKyivTimeZone(), endDate.AsKyivTimeZone());
            }
            else
            {
                if (!CheckCanModify(await CampaignsDb.GetCampaignById(camId), out var fault)) return fault!;
                await CampaignsDb.UpdateCampaign(camId, camName, startDate.AsKyivTimeZone(), endDate.AsKyivTimeZone());
            }
            return BackToList();
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            if (!CheckRole(out var failed)) return failed!;
            if (!CheckCanModify(await CampaignsDb.GetCampaignById(id), out var fault)) return fault!;
            await CampaignsDb.DeleteCampaign(id);
            return BackToList();
        }

        private bool CheckCanModify(Campaign c, out IActionResult? fault)
        {
            if (!(c.State == Campaign.CampaignState.Future || LoginData?.AccessLevel == Login.AccessLevelCode.Admin))
            {
                fault = BadRequest("Unable to edit campaign, state = " + c.UfState);
                return false;
            }
            fault = null;
            return true;
        }
    }
}

Pages/Candidates.cshtml.cs
using eVybir.Infra;
using eVybir.Pages.Shared;
using eVybir.Repos;
using Microsoft.AspNetCore.Mvc;

namespace eVybir.Pages
{
    public class CandidatesModel : LoginAwareCrudPage
    {
        public override string Title => "Candidates";

        public override Type PageType => typeof(Pages_Candidates);

        public async Task<IActionResult> OnPost(int candId, string candName, DateTime? candDate, string? candDesc, Candidate.EntryType candKind) 
        {
            if (!CheckRole(out var failed)) return failed!;
            if (candId == DEFAULT_ID)
            {
                await CandidatesDb.AddCandidate(candName, candDate, candDesc, candKind);
            }
            else
            {
                if (!CheckCanModify(await CandidatesDb.GetCandidateHasPastUsesById(candId), false, out var fault)) return fault!;
                await CandidatesDb.UpdateCandidate(candId, candName, candDate, candDesc, candKind);
            }
            return BackToList();
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            if (!CheckRole(out var failed)) return failed!;
            if (!CheckCanModify(await CandidatesDb.GetCandidateHasPastUsesById(id), true, out var fault)) return fault!;
            await CandidatesDb.DeleteCandidate(id);
            return BackToList();
        }

        private bool CheckCanModify(bool isUsed, bool deleting, out IActionResult? fault)
        {
            if (isUsed && (deleting || LoginData?.AccessLevel != Login.AccessLevelCode.Admin))
            {
                fault = BadRequest("Unable to edit candidate, used in past Campaigns!");
                return false;
            }
            fault = null;
            return true;
        }
    }
}

Pages/CheckVoter.cshtml.cs
using eVybir.Pages.Shared;
using eVybir.Repos;
using Microsoft.AspNetCore.Mvc;

namespace eVybir.Pages
{
    public class CheckVoterModel : LoginAwarePageBase
    {
        public override string Title => "Бюлетені громадянина";

        public int? VoterId { get; set; }

        public IActionResult OnGet(int? id)
        {
            if (!CheckRole<Pages_CheckVoter>(out var failed)) return failed!;
            VoterId = id;
            return Page();
        }

        public async Task<IActionResult> OnPostRegister(int id, int campaignId)
        {
            if (!CheckRole<Pages_CheckVoter>(out var failed)) return failed!;
            await TicketsDb.Register(campaignId, id, true);
            return RedirectToPage(Location<Pages_CheckVoter>());
        }

        public async Task<IActionResult> OnPostCancel(int id, Guid ticketId)
        {
            if (!CheckRole<Pages_CheckVoter>(out var failed))
                return failed!;
            else if (await TicketsDb.CancelTicket(ticketId, id))
                return RedirectToPage(Location<Pages_CheckVoter>());
            else
                return BadRequest("Ticket was not cancelled, try again");
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace eVybir.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Pages/Index.cshtml.cs
using eVybir.Pages.Shared;
using Microsoft.AspNetCore.Mvc;

namespace eVybir.Pages
{
    public class IndexModel : LoginAwarePageBase
    {
        public override string Title => "Home page";

        public async Task<IActionResult> OnPostLogin(string userId)
        {
            await LoginUser(userId);
            return RedirectToPage(Location<Pages_Index>());
        }
    }
}

Pages/ManageCampaign.cshtml.cs
using eVybir.Infra;
using eVybir.Pages.Shared;
using eVybir.Repos;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace eVybir.Pages
{
    public class ManageCampaignModel : LoginAwarePageBase
    {
        public override string Title => "Призначити кандидатів";

        public List<DbWrapped<int, Campaign>> Campaigns { get; private set; }

        public bool ShowOnlyList { get; private set; } = true;

        public int CurrentCampaignId { get; private set; }

        public List<DbWrapped<int, Candidate>> Candidates { get; private set; } 

        public List<Participant> ParticipantsRoot { get; private set; } 

        public int[] IncludedCandidateIds { get; private set; }

        public int[] SortedCandidateIds { get; private set; }

        public Campaign CurrentCampaign{ get; private set; }


        public async Task<IActionResult> OnGet(int? id)
        {
            if (!CheckRole<Pages_ManageCampaign>(out var failed)) return failed!;
            Campaigns = await CampaignsDb.GetAllCampaigns().ToListAsync();
            if (id.HasValue)
            {
                CurrentCampaignId = id.Value;
                var campaign = Campaigns.FirstOrDefault(c => c.Key == CurrentCampaignId)?.Entity;
                if (campaign == null) // wrong, race condition etc.
                {
                    return RedirectToPage(Location<Pages_ManageCampaign>());
                }
                CurrentCampaign = campaign;
                ShowOnlyList = false;
                Candidates = await CandidatesDb.GetCandidates().ToListAsync();
                ParticipantsRoot = await CampaignCandidatesDb.GetParticipantsByCampaignFlat(CurrentCampaignId).ToListAsync();
                IncludedCandidateIds = ParticipantsRoot.Select(p => p.CandidateId).ToArray();
                SortedCandidateIds = Candidates.Select(c => c.Key).ToArray();
                for (int i = ParticipantsRoot.Count - 1; i >= 0; i--)
                {
                    var participant = ParticipantsRoot[i];
                    if (participant.GroupId.HasValue)
                    {
                        ParticipantsRoot.RemoveAt(i);
                        ParticipantsRoot.First(p => p.CandidateId == participant.GroupId.Value).Children.Insert(0, participant);
                    }
                }
            }
            return Page();
        }

        public async Task<IActionResult> OnPost(int? id, string inclusionModel)
        {
            if (!CheckRole<Pages_ManageCampaign>(out var failed)) return failed!;
            if (!id.HasValue) return NotFound();
            var c = await CampaignsDb.GetCampaignById(id.Value);
            if (c.State != Campaign.CampaignState.Future) return BadRequest("Unable to edit, campaign state is " + c.UfState);
            var updateModel = JsonSerializer.Deserialize<List<Participant>>(inclusionModel)!;
            for (int i = updateModel.Count-1; i >= 0 ; i--)
            {
                var chCol = updateModel[i].Children;
                for (int j = chCol.Count -1; j >= 0; j--)
                {
                    updateModel.Add(chCol[j]);
                    chCol.RemoveAt(j);
                }
            }
            await CampaignCandidatesDb.UpdateCampaignData(id.Value, updateModel);
            return RedirectToPage(Location<Pages_ManageCampaign>(), new { id = (int?)null });
        }
    }
}

Pages/Privacy.cshtml.cs
using eVybir.Pages.Shared;

namespace eVybir.Pages
{
    public class PrivacyModel : LoginAwarePageBase
    {
        public override string Title => "Політика конфіденційності";
    }
}

Pages/Register.cshtml.cs
using eVybir.Pages.Shared;
using eVybir.Repos;
using Microsoft.AspNetCore.Mvc;

namespace eVybir.Pages
{
    public class RegisterModel : LoginAwareCrudPage
    {
        public override Type PageType => typeof(Pages_Register);

        public override string Title => "Бюлетені";

        public async Task<IActionResult> OnPostRegister(int campaignId) 
        {
            if (!CheckRole(out var failed)) return failed!;
            await TicketsDb.Register(campaignId, LoginData!.Id, false);
            return BackToList();
        }

        public async Task<IActionResult> OnPostCancel(Guid ticketId) 
        {
            if (!CheckRole(out var failed))
                return failed!;
            else if (await TicketsDb.CancelTicket(ticketId, LoginData!.Id))
                return BackToList();
            else
                return BadRequest("Ticket was not cancelled, try again");
        }
    }
}

Pages/Report.cshtml.cs
using eVybir.Infra;
using eVybir.Pages.Shared;
using eVybir.Repos;
using Microsoft.AspNetCore.Mvc;

namespace eVybir.Pages
{
    public class ReportModel : LoginAwarePageBase
    {
        public override string Title => "Виборчі звіти";

        public Dictionary<int, Campaign> Campaigns { get; private set; }

        public int? CurrentCampaignId { get; private set; }

        public bool CampaignIsActive { get; private set; }

        public TicketStats TicketStats { get; private set; }

        public List<DbWrapped<int, Candidate>> VoteStats { get; private set; }

        public List<GroupMembersStats>? GroupMembersStats { get; set; }

        public int MaxVote { get; set; }

        public async Task <IActionResult> OnGet(int? id)
        {
            if (!id.HasValue && !Request.Path.Value!.EndsWith('/'))
                return Redirect(Location<Pages_Report>() + "/");
            Campaigns = await CampaignsDb.GetPastOrCurrentCampaigns().ToDictionaryAsync(db => db.Key, db => db.Entity);
            CurrentCampaignId = id;
            if (id.HasValue)
            {
                if (!Campaigns.TryGetValue(id.Value, out Campaign? thisCampaign))
                    return NotFound();
                CampaignIsActive = thisCampaign.End > DateTime.UtcNow; //.state == Ongoing does 2 datetime comparisons, this line does it in 1
                TicketStats = await ReportDb.GetTicketStats(id.Value);
                VoteStats = await ReportDb.GetVoteStats(id.Value).ToListAsync();
                TicketStats.VotesCast = VoteStats.Sum(v => v.Key);
                MaxVote = VoteStats.Count > 0 ? VoteStats.Max(v => v.Key) : 0;
                if (await ReportDb.IsCampaignIncludingGroupMembers(id.Value))
                {
                    GroupMembersStats = await ReportDb.GetGroupMemberStats(id.Value).ToListAsync();
                }
            }
            return Page();
        }
    }
}

Pages/Users.cshtml.cs
using eVybir.Infra;
using eVybir.Pages.Shared;
using eVybir.Repos;
using Microsoft.AspNetCore.Mvc;

namespace eVybir.Pages
{
    public class UsersModel : LoginAwareCrudPage
    {
        public override string Title => "Manage Users";

        public override Type PageType => typeof(Pages_Users);

        public async Task<IActionResult> OnPostToggle(int id, bool currentState) 
        {
            if (!CheckRole(out var failed)) return failed!;
            await PermissionsDb.SetActive(id, !currentState);
            return BackToList();
        }

        public async Task<IActionResult> OnPost(int userId, Login.AccessLevelCode userRole)
        {
            if (!CheckRole(out var failed)) return failed!;
            await PermissionsDb.AddUser(userId, userRole);
            return BackToList();
        }
    }
}

Pages/Vote.cshtml.cs
using eVybir.Infra;
using eVybir.Pages.Shared;
using eVybir.Repos;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace eVybir.Pages
{
    public class VoteModel : LoginAwarePageBase
    {
        public override string Title => "Віддати голос";

        public Bulletin Bulletin { get; set; }

        public bool IsPartyListBasedElection { get; set; } = false;

        public int CampaignId { get; set; }

        public async Task<IActionResult> OnGet(Guid id)
        {
            if (!CheckRole<Pages_Vote>(out var failed)) return failed!;
            var grp = await TicketsDb.GetBulletinByTicket(id)
                                     .GroupBy(b => b.Location.GroupId)
                                     .ToListAsync();
            CampaignId = grp[0].First().CampaignId;
            Bulletin = new(await CampaignsDb.GetCampaignById(CampaignId),
                           grp.Single(g => g.Key == null)
                              .Select(b => new BulletinHierarchy(b,
                                                                 grp.FirstOrDefault(g => g.Key == b.Location.CandidateId)?.ToArray() ?? []))
                              .ToArray());
            IsPartyListBasedElection = Bulletin.PrimaryEntries.Any(e => e.Children.Length > 0);
            return Page();
        }

        public async Task<IActionResult> OnPost(Guid id, int campaignId, string castIds)
        {
            if (!CheckRole<Pages_Vote>(out var failed)) 
                return failed!;
            else if (await TicketsDb.Vote(id, campaignId, JsonSerializer.Deserialize<int[]>(castIds)!))
                return Redirect(Location<Pages_Register>());
            else
                return BadRequest("The vote was not cast, try again");
        }
    }
}

Pages/Campaigns.cshtml
@page
@model eVybir.Pages.CampaignsModel
@{
    Model.SetPageData(ViewData);
}
<div>
    <h1 class="text-center">Реєстрація виборчих подій</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Повна назва</th>
                <th>Початок голосування</th>
                <th>Закінчення голосування</th>
                <th>Дії</th>
            </tr>
        </thead>
        <tbody>
            @await foreach (var camp in CampaignsDb.GetAllCampaigns())
            {
                <tr>
                    <td>@camp.Entity.Name</td>
                    <td>@camp.Entity.Start</td>
                    <td>@camp.Entity.End</td>
                    <td>
                        @if(camp.Entity.State == Campaign.CampaignState.Future || Model.LoginData?.AccessLevel == Login.AccessLevelCode.Admin)
                        {
                            <form method="post" asp-page-handler="delete" class="@(camp.Entity.State != Campaign.CampaignState.Future ? "adminOnlyEdit" : "")">
                                <input type="hidden" name="id" value="@camp.Key" />
                                <input type="button" value="✒️Редагувати" onclick="editCampaign(@camp.Key, '@camp.Entity.Name', '@(camp.Entity.Start.ToString("yyyy-MM-ddTHH:mm"))', '@(camp.Entity.End.ToString("yyyy-MM-ddTHH:mm"))')" />
                                <input type="submit" value="❌Видалити" />
                            </form>
                        } 
                        else
                        {
                            @camp.Entity.UfState
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p class="text-bg-secondary text-warning text-center">Увага! При видаленні події також видаляється її список кандидатів!</p>
</div>

<div>
    <h3>Додати виборчу подію</h3>
    <form method="post">
        <input type="hidden" id="camId" name="camId" value="@LoginAwareCrudPage.DEFAULT_ID" />
        <table class="table-sm">
            <tr>
                <td><label for="camName">Повна назва:</label></td>
                <td><input type="text" id="camName" name="camName" maxlength="200" size="50" required /></td>
            </tr>
            <tr>
                <td><label for="startDate">Початок голосування:</label></td>
                <td><input type="datetime-local" id="startDate" name="startDate" required /></td>
            </tr>
            <tr>
                <td><label for="endDate">Закінчення голосування:</label></td>
                <td><input type="datetime-local" id="endDate" name="endDate" required /></td>
            </tr>
            <tr>
                <td class="text-bg-secondary text-warning">Увага! Час зазначено по Києву!</td>
                <td align="right">
                    <input type="submit" value="Відправити" />
                </td>
            </tr>
        </table>
    </form>
</div>

Pages/Candidates.cshtml
@page
@model eVybir.Pages.CandidatesModel
@{
    Model.SetPageData(ViewData);
}

<div>
    <h1 class="text-center">База Кандидатів та Членів Партій чи Груп</h1>
    <table class="table">
        <thead>
            <tr>
                <th>ПІБ чи назва</th>
                <th>Дата народження чи створення</th>
                <th>Опис</th>
                <th>Тип</th>
                <th>Дії</th>
            </tr>
        </thead>
        <tbody>
            @await foreach (var cand in CandidatesDb.GetCandidatesWithUse())
            {
                var cData = cand.Entity;
                var cId = cand.Key.Item1;
                var cUsedInPast = cand.Key.Item2;
                <tr>
                    <td>@cData.Name</td>
                    <td>@(cData.Date.HasValue ? cData.Date.Value.ToShortDateString() : "(Не вказано)")</td>
                    <td class="ws-pre">@cData.Description</td>
                    <td>@cData.UfEntryKind</td>
                    <td>
                        @if(cUsedInPast == 0 || Model.LoginData?.AccessLevel == Login.AccessLevelCode.Admin)
                        {
                            <form method="post" asp-page-handler="delete" class="@(cUsedInPast > 0 ? "adminOnlyEdit" : "")">
                                <input type="hidden" name="id" value="@cId" />
                                <input type="button" value="✒️Редагувати" onclick="editCandidate(@cId, '@cData.Name', @(cData.Date.HasValue? "'" + cData.Date.Value.ToString("yyyy-MM-dd") + "'" : "null"), @cData.Description.JsEscape(), '@cData.EntryKind')" />
                                @if(cUsedInPast == 0)
                                {
                                    <input type="submit" value="❌Видалити" />
                                }
                            </form>
                        }
                        else
                        {
                            <p>Внесено до бюлетеней, заблокованих від змін: @cUsedInPast.</p>
                        }
                    </td>
                </tr>
             }
        </tbody>
    </table>
</div>

<div>
    <h3>Додати кандидата</h3>
    <form method="post">
        <input type="hidden" id="candId" name="candId" value="@LoginAwareCrudPage.DEFAULT_ID" />
        <table class="table-sm">
            <tr>
                <td><label for="candName">ПІБ чи назва:</label></td>
                <td><input type="text" id="candName" name="candName" maxlength="200" size="50" required /></td>
            </tr>
            <tr>
                <td><label for="candDate">Дата народження чи створення:</label></td>
                <td><input type="date" id="candDate" name="candDate" /></td>
            </tr>
            <tr>
                <td><label for="candDesc">Опис:</label></td>
                <td><textarea id="candDesc" name="candDesc" width="500" class="w-100" > </textarea> </td>
            </tr>
            <tr>
                <td><label for="candKind">Тип:</label></td>
                <td>
                    <select id="candKind" name="candKind">
                        @foreach (var id in Enum.GetValues<Candidate.EntryType>().Except([Candidate.EntryType.Unknown]))
                        {
                            <option value="@id">@Candidate.HumanizeEntryType(id)</option>
                        }
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2" align="right">
                    <input type="submit" value="Відправити" />
                </td>
            </tr>
        </table>
    </form>
</div>

Pages/CheckVoter.cshtml
@page "{id:int?}"
@model eVybir.Pages.CheckVoterModel
@{
    Model.SetPageData(ViewData);
}
<div>
    <h1 class="text-center">Виборчі бюлетені громадянина(ки)</h1>
    <script>
        function getHref(inp) {
            return '@(LoginAwarePageBase.Location<Pages_CheckVoter>())' + (inp.value != '' ? '/' + inp.value : '');
        }
    </script>
    <label for="voterUserId">Введіть ID громадянина(ки):</label>
    <input type="number" name="voterUserId" id="voterUserId" tabindex="1"
           onchange="document.getElementById('switchUser').href=getHref(this);" 
           onkeypress="if(event.key=='Enter') location.href=getHref(this);"/>
    <a href="#" tabindex="2" id="switchUser">Перейти</a>
    @if (Model.VoterId.HasValue)
    {
        <span>|</span> <a tabindex="3" href="@(LoginAwarePageBase.Location<Pages_CheckVoter>())">Скинути</a>
    }
    <hr />

    @if (Model.VoterId.HasValue)
    {
        <p class="bg-warning text-dark text-center">Увага! Перелік наведено для громадянина(ки) ID @Model.VoterId.Value!</p>
        <table class="table">
            <thead>
                <tr>
                    <th>Вибори <span class="badge bg-info text-dark">активні</span></th>
                    <th>Бюлетень отримано</th>
                    <th>Тип голосування</th>
                    <th>Голос віддано</th>
                    <th>Дії</th>
                </tr>
            </thead>
            <tbody>
                @await foreach (var ct in TicketsDb.GetUserCampaignsStatus(Model.VoterId.Value, true))
                {
                    <tr>
                        <td>@ct.CampaignName</td>
                        <td>@ct.UfTicketReceived</td>
                        <td>@ct.UfTicketSource</td>
                        <td>@ct.UfTicketCommitted</td>
                        <td>
                            @if (ct.Ticket == null)
                            {
                                <form method="post" asp-page-handler="register">
                                    <input type="hidden" name="campaignId" value="@ct.CampaignId" />
                                    <input type="submit" value="Видати бюлетень" class="btn-primary" />
                                </form>
                            }
                            else if (ct.Ticket.TicketCommittedDate.HasValue)
                            {
                                <span class="text-success">Голос вже віддано!</span>
                            }
                            else if (!ct.Ticket.IsTicketOffline)
                            {
                                <span>(Недоступно - скасувати бюлетень виданий онлайн може лише сам громадянин)</span>
                            }
                            else
                            {
                                <form method="post" asp-page-handler="cancel">
                                    <input type="hidden" name="ticketId" value="@ct.Ticket.TicketId" />
                                    <input type="submit" value="Скасувати бюлетень" class="btn-secondary"/>
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

Pages/Register.cshtml
@page
@model eVybir.Pages.RegisterModel
@{
    Model.SetPageData(ViewData);
}
<div>
    <h1 class="text-center">Виборчі бюлетені</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Вибори</th>
                <th>Бюлетень отримано</th>
                <th>Тип голосування</th>
                <th>Голос віддано</th>
                <th>Дії</th>
            </tr>
        </thead>
        <tbody>
            @await foreach (var ct in TicketsDb.GetUserCampaignsStatus(Model.LoginData!.Id, false))
            {
                <tr>
                    <td>@ct.CampaignName @if(ct.IsCampaignFinished){<span class="badge bg-info text-dark">- завершено</span>}</td>
                    <td>@ct.UfTicketReceived</td>
                    <td>@ct.UfTicketSource</td>
                    <td>@ct.UfTicketCommitted</td>
                    <td>
                        @if (!ct.IsCampaignFinished && ct.Ticket?.TicketCommittedDate == null)
                        {
                            @if(ct.Ticket == null)
                            {
                                <form method="post" asp-page-handler="register">
                                    <input type="hidden" name="campaignId" value="@ct.CampaignId" />
                                    <input type="submit" value="Отримати бюлетень" class="btn btn-primary" />
                                </form>
                            }
                            else if(ct.Ticket.IsTicketOffline)
                            {
                                <span>(Недоступно: голосуйте офлайн; для голосування онлайн, скасуйте бюлетень виданий оффлайн, звернувшись до членів ТВК)</span>
                            }
                            else
                            {
                                <form method="post" asp-page-handler="cancel">
                                    <input type="hidden" name="ticketId" value="@ct.Ticket.TicketId" />
                                    <a class="btn btn-primary" href="/Vote/@ct.Ticket.TicketId">Голосувати</a>
                                    <input type="submit" value="Скасувати бюлетень" class="btn btn-secondary"/>
                                </form>
                            }
                        }
                        else if(ct.Ticket?.TicketCommittedDate !=  null || (ct.Ticket?.IsTicketOffline == true && ct.IsCampaignFinished))
                        {
                            <span class="text-success">Дякуємо за волевиявлення!</span>
                        }
                        else if(ct.Ticket == null)
                        {
                            <span class="text-muted">Ви не приймали участь в голосуванні.</span>
                        }
                        else if(ct.Ticket.TicketCommittedDate == null)
                        {
                            <span class="text-muted">Нажаль, ви не скористалися виданим бюлетенем.</span>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Pages/Users.cshtml
@page
@model UsersModel
@{
    Model.SetPageData(ViewData);
}

<div>
    <h1 class="text-center">Зареєстровані користувачі</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Ідентифікатор</th>
                <th>Роль</th>
                <th>ПІБ</th>
                <th>Примітки</th>
                <th>Дії</th>
            </tr>
        </thead>
        <tbody>
            @await foreach (var user in PermissionsDb.GetUsers())
            {
                <tr>
                    <td>@user.Entity.Id</td>
                    <td>@user.Entity.Role</td>
                    <td>@user.Entity.Name</td>
                    <td>@if (!user.Entity.Enabled) { <span class="invalid-feedback d-inline">ЗАБЛОКОВАНО</span> }</td>
                    <td>
                        @if (user.Entity.Id != Model.LoginData?.Id)
                        {
                            <form method="post" asp-page-handler="toggle">
                                <input type="hidden" name="id" value="@user.Key" />
                                <input type="hidden" name="currentState" asp-for="@user.Entity.Enabled" />
                                @if (user.Entity.Enabled)
                                {
                                    <input type="submit" value="⭕Заблокувати" />
                                }
                                else
                                {
                                    <input type="submit" value="Розблокувати" />
                                }
                            </form>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <h3>Роєстрація користувача</h3>
    <form method="post">
        <table>
            <tr>
                <td><label for="userId">ID користувача:</label></td>
                <td><input type="number" id="userId" name="userId" required/></td>
            </tr>
            <tr>
                <td><label for="userRole">Роль:</label></td>
                <td>
                    <select id="userRole" name="userRole">
                        @foreach (var id in Enum.GetValues<Login.AccessLevelCode>().Except([Login.AccessLevelCode.None]))
                        {
                            <option value="@id">@Login.HumanizeAccessLevelCode(id)</option>
                        }
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2" align="right">
                    <input type="submit" value="Відправити" />
                </td>
            </tr>
        </table>
    </form>
</div>